[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli_client"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
logger.workspace = true
log.workspace = true

uuid.workspace = true
clap = "4.5.16"
