[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
shared = { path = "../shared" }
logger.workspace = true
log.workspace = true
uuid.workspace = true
time.workspace = true
networking.workspace = true
rodio.workspace = true
ctrlc = "3.4.5"
spin_sleep_util = "0.1.1"