[package]
name = "models"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"


# [profile.dev]
# opt-level = 3
# debug = 0
# overflow-checks = false
# debug-assertions = false
# incremental = true

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
